on:
  pull_request:
    branches:
      - main
    types:
      - assigned
      - opened
      - synchronize
      - reopened

env:
  CTEST_NO_TESTS_ACTION: error
  CTEST_PARALLEL_LEVEL: 0
  CMAKE_BUILD_PARALLEL_LEVEL: 4
  HOMEBREW_NO_INSTALL_CLEANUP: 1

name: Test
jobs:
  tests:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-24.04, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Install Lets
        uses: lets-cli/lets-action@v1.1
        with:
          version: latest
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run tests
        run: lets test
  lints:
    runs-on: ubuntu-24.04
    steps:
      - name: Install Lets
        uses: lets-cli/lets-action@v1.1
        with:
          version: latest
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run linter
        run: lets lint
